Gradle update
zetaapps/utils pull request #5
Opened 2017-07-16 15:02 UTC by manjunathc23

Little clean up's and gradle update.

2017-07-16 18:38 UTC, manijshrestha requested changes
Some nit comments.

2017-07-16 18:38 UTC, manijshrestha commented on dependencies.gradle
> +        lottieAnimationVersion                : "1.5.1",
👍

2017-07-16 18:38 UTC, manijshrestha commented on dependencies.gradle
> +        fabricPlugin      : "io.fabric.tools:gradle:$versions.fabricPluginVersion",
I suggest we only use the one that are truly used to to keep in simple.

2017-07-16 18:38 UTC, manijshrestha commented on zetautils/build.gradle
> +            minifyEnabled true
this is intentional?, minify debug? Do note, release is non minified here.

2017-07-17 02:01 UTC, manjunathc23 commented on dependencies.gradle
> +        fabricPlugin      : "io.fabric.tools:gradle:$versions.fabricPluginVersion",
Sounds good. Will remove cmd c + cmd v changes.

2017-07-17 02:02 UTC, manjunathc23 commented on zetautils/build.gradle
> +            minifyEnabled true
Oops it should be other way round.

2017-07-17 02:02 UTC, manjunathc23 commented on dependencies.gradle
> +        lottieAnimationVersion                : "1.5.1",
Cleaning this up.

2017-07-17 02:07 UTC, manjunathc23 commented
@manijshrestha  : Addressed the code reviews, please take a look now.

2017-07-17 04:26 UTC, manijshrestha approved these changes

2017-07-17 04:32 UTC, merged